/**
 * seed.ts — populates the exercises table on first install.
 * Triggered once by App.tsx when db.exercises.count() === 0.
 * Module-level flag guards against React Strict Mode double-invocation.
 *
 * Source: artifacts/seed-draft.md (sessions 45a–g + Session 48 P1 catch-up, 214 tagged entries).
 * Curation rules: artifacts/seed-tagging-principles.md.
 *
 * 2-pass insert: parents first, then variants resolve parentExerciseId via name lookup.
 * Muscle inheritance for variants flagged "// inherit from parent" in the markdown
 * is pre-resolved at compile time — variant entries below carry the parent's
 * primary/secondary arrays inlined. Only the FK is runtime-resolved.
 */
import { db } from './db';
import type { Exercise, Muscle, SecondaryMuscle } from '../types';

let seedStarted = false;

// ── Helpers ────────────────────────────────────────────────────────────────

const s = (m: Muscle): SecondaryMuscle => ({ muscle: m, role: 'synergist' });
const b = (m: Muscle): SecondaryMuscle => ({ muscle: m, role: 'stabilizer' });

type SeedEntry = Omit<Exercise, 'id' | 'parentExerciseId'> & {
  parentName: string | null;
};

type Tier3 = Partial<Pick<Exercise, 'gripWidth' | 'gripOrientation' | 'stanceWidth' | 'bias'>>;

function e(
  name: string,
  parentName: string | null,
  primary: Muscle[],
  secondary: SecondaryMuscle[],
  equipment: string | null,
  tier3: Tier3 = {},
): SeedEntry {
  return {
    name,
    isCustom: false,
    parentName,
    primaryMuscles: primary,
    secondaryMuscles: secondary,
    equipment,
    gripWidth: tier3.gripWidth ?? null,
    gripOrientation: tier3.gripOrientation ?? null,
    stanceWidth: tier3.stanceWidth ?? null,
    bias: tier3.bias ?? null,
    jointLoad: [],
  };
}

// ── Catalog (214 entries) ──────────────────────────────────────────────────

export const SEED_ENTRIES: SeedEntry[] = [
  // ── Session 45a: 11 parents ──
  e('Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs'), b('calves')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Deadlift', null, ['glutes', 'hamstrings'],
    [s('quads'), b('lowerBack'), b('upperBack'), b('forearms')],
    'barbell'),
  e('Bench Press', null, ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff'), b('lats')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Dips', null, ['chest', 'triceps'],
    [s('frontDelts'), b('upperBack'), b('rotatorCuff')],
    'bodyweight'),
  e('Pull-Up', null, ['lats', 'upperBack'],
    [s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'bodyweight', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Lat Pulldown', null, ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'cable', { gripWidth: 'wide', gripOrientation: 'pronated' }),
  e('Romanian Deadlift', null, ['glutes', 'hamstrings'],
    [b('upperBack'), b('lowerBack'), b('abs'), b('forearms')],
    'barbell'),
  e('Skull Crusher', null, ['triceps'],
    [b('forearms'), b('rotatorCuff')],
    'barbell'),
  e('Barbell Curl', null, ['biceps'],
    [s('brachialis'), s('forearms'), b('abs')],
    'barbell', { gripOrientation: 'supinated' }),
  e('Plank', null, ['abs'],
    [b('obliques'), b('glutes'), b('frontDelts'), b('rotatorCuff')],
    'bodyweight'),
  e('Cable Crossover', null, ['chest'],
    [s('frontDelts'), b('rotatorCuff')],
    'cable'),

  // ── Session 45b: 18 Seed (incl. OHP missed parent) + 9 P0 ──
  e('Overhead Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus'), b('rotatorCuff'), b('abs')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Incline Barbell Bench Press', null, ['chest'],
    [s('frontDelts'), s('triceps'), b('rotatorCuff'), b('serratus')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Dumbbell Fly', null, ['chest'],
    [s('frontDelts'), b('rotatorCuff')],
    'dumbbell'),
  e('Push-Up', null, ['chest'],
    [s('triceps'), s('frontDelts'), s('serratus'), b('abs'), b('rotatorCuff')],
    'bodyweight'),
  e('Bent-Over Barbell Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Seated Cable Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'cable', { gripOrientation: 'neutral' }),
  e('Leg Press', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine'),
  e('Lying Leg Curl', null, ['hamstrings'],
    [s('calves')],
    'machine'),
  e('Leg Extension', null, ['quads'],
    [],
    'machine'),
  e('Standing Calf Raise (Bodyweight)', null, ['calves'],
    [],
    'bodyweight'),
  e('Lateral Raise', null, ['sideDelts'],
    [s('upperTraps'), b('rotatorCuff')],
    'dumbbell'),
  e('Front Raise', null, ['frontDelts'],
    [s('upperTraps')],
    'dumbbell'),
  e('Face Pull', null, ['rearDelts'],
    [s('upperBack'), s('upperTraps'), s('rotatorCuff')],
    'cable', { gripOrientation: 'pronated' }),
  e('Hammer Curl', null, ['biceps', 'brachialis'],
    [s('forearms'), b('abs')],
    'dumbbell', { gripOrientation: 'neutral' }),
  e('Tricep Pushdown', null, ['triceps'],
    [b('forearms'), b('frontDelts')],
    'cable', { gripOrientation: 'pronated' }),
  e('Crunch', null, ['abs'],
    [],
    'bodyweight'),
  e('Hanging Leg Raise', null, ['abs', 'hipFlexors'],
    [b('obliques'), b('forearms')],
    'bodyweight'),
  e('Ab Wheel Rollout', null, ['abs'],
    [s('lats'), b('obliques'), b('triceps'), b('serratus')],
    'other'),
  e('Dumbbell Bench Press', null, ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff')],
    'dumbbell'),
  e('Incline Dumbbell Bench Press', null, ['chest'],
    [s('frontDelts'), s('triceps'), b('rotatorCuff'), b('serratus')],
    'dumbbell'),
  e('Dumbbell Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'dumbbell', { gripOrientation: 'neutral' }),
  // Chin-Up: variant of Pull-Up with DIVERGENT map (Rule 1 override)
  e('Chin-Up', 'Pull-Up', ['lats', 'biceps'],
    [s('brachialis'), s('upperBack'), s('rearDelts'), b('forearms')],
    'bodyweight', { gripWidth: 'medium', gripOrientation: 'supinated' }),
  e('Bulgarian Split Squat', null, ['quads', 'glutes'],
    [s('adductors'), s('hamstrings'), b('calves'), b('abs')],
    'dumbbell'),
  e('Barbell Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs')],
    'barbell'),
  e('Dumbbell Shoulder Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus'), b('rotatorCuff'), b('abs')],
    'dumbbell'),
  e('Barbell Shrug', null, ['upperTraps'],
    [b('forearms'), b('lowerBack'), b('neck')],
    'barbell', { gripOrientation: 'pronated' }),
  e('Dumbbell Curl', null, ['biceps'],
    [s('brachialis'), s('forearms'), b('abs')],
    'dumbbell', { gripOrientation: 'supinated' }),

  // ── Session 45c: 27 P1 upper-body ──
  e('Decline Bench Press', null, ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff'), b('lats')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Machine Chest Press', null, ['chest'],
    [s('triceps'), s('frontDelts')],
    'machine'),
  e('Pec Deck', null, ['chest'],
    [s('frontDelts')],
    'machine'),
  e('Close-Grip Bench Press', null, ['chest', 'triceps'],
    [s('frontDelts'), b('rotatorCuff'), b('lats')],
    'barbell', { gripWidth: 'narrow', gripOrientation: 'pronated' }),
  e('Machine Assisted Dip', null, ['chest', 'triceps'],
    [s('frontDelts')],
    'machine'),
  e('Iso-Lateral Chest Press', null, ['chest'],
    [s('triceps'), s('frontDelts')],
    'machine'),
  e('Chest-Supported Dumbbell Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms')],
    'dumbbell', { gripOrientation: 'neutral' }),
  e('T-Bar Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'barbell', { gripOrientation: 'neutral' }),
  e('Iso-Lateral High Row', null, ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'machine'),
  e('Iso-Lateral Low Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms')],
    'machine'),
  e('Machine Assisted Pull-Up', null, ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'machine'),
  e('Arnold Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus'), b('rotatorCuff'), b('abs')],
    'dumbbell'),
  e('Machine Shoulder Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus')],
    'machine'),
  e('Cable Lateral Raise', null, ['sideDelts'],
    [s('upperTraps'), b('rotatorCuff')],
    'cable'),
  e('Rear Delt Pec Deck', null, ['rearDelts'],
    [s('upperBack')],
    'machine'),
  e('Bent-Over Dumbbell Reverse Fly', null, ['rearDelts'],
    [s('upperBack'), b('lowerBack')],
    'dumbbell'),
  e('Dumbbell Shrug', null, ['upperTraps'],
    [b('forearms'), b('lowerBack'), b('neck')],
    'dumbbell', { gripOrientation: 'neutral' }),
  e('Landmine Press', null, ['frontDelts'],
    [s('chest'), s('triceps'), s('serratus'), b('obliques')],
    'barbell'),
  e('Iso-Lateral Shoulder Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus')],
    'machine'),
  e('Upright Row', null, ['sideDelts'],
    [s('upperTraps'), s('frontDelts'), s('biceps'), b('rotatorCuff')],
    'barbell', { gripWidth: 'shoulder', gripOrientation: 'pronated' }),
  e('EZ-Bar Curl', null, ['biceps'],
    [s('brachialis'), s('forearms'), b('abs')],
    'barbell', { gripOrientation: 'supinated' }),
  e('Preacher Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'barbell', { gripOrientation: 'supinated' }),
  e('Incline Dumbbell Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'dumbbell', { gripOrientation: 'supinated' }),
  e('Cable Curl', null, ['biceps'],
    [s('brachialis'), s('forearms'), b('abs')],
    'cable', { gripOrientation: 'supinated' }),
  e('Machine Preacher Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'machine', { gripOrientation: 'supinated' }),
  e('Overhead Cable Extension', null, ['triceps'],
    [b('forearms'), b('rotatorCuff')],
    'cable', { gripOrientation: 'neutral' }),
  e('Overhead Dumbbell Extension', null, ['triceps'],
    [b('forearms'), b('rotatorCuff')],
    'dumbbell', { gripOrientation: 'neutral' }),
  // Session 48 catch-up — 2 P1 entries surfaced in 212→214 curation gap audit
  e('Machine Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms')],
    'machine'),
  // Neutral-Grip Pull-Up: structural variant of Pull-Up, pure inheritance (no Rule 1 override)
  e('Neutral-Grip Pull-Up', 'Pull-Up', ['lats', 'upperBack'],
    [s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'bodyweight', { gripOrientation: 'neutral' }),

  // ── Session 45d: 27 P1 lower-body + core ──
  e('Trap Bar Deadlift', null, ['glutes', 'hamstrings'],
    [s('quads'), b('upperBack'), b('lowerBack'), b('forearms')],
    'barbell', { gripOrientation: 'neutral' }),
  e('Sumo Deadlift', null, ['glutes', 'hamstrings'],
    [s('adductors'), s('quads'), b('upperBack'), b('lowerBack'), b('forearms')],
    'barbell', { stanceWidth: 'sumo', gripOrientation: 'pronated' }),
  e('Stiff-Leg Deadlift', null, ['glutes', 'hamstrings'],
    [b('upperBack'), b('lowerBack'), b('abs'), b('forearms')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Front Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('upperBack'), b('abs'), b('lowerBack')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Goblet Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('upperBack'), b('abs')],
    'dumbbell', { stanceWidth: 'shoulder' }),
  e('Hack Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine'),
  e('Walking Lunge', null, ['quads', 'glutes'],
    [s('hamstrings'), s('adductors'), b('calves'), b('abs')],
    'dumbbell'),
  e('Reverse Lunge', null, ['quads', 'glutes'],
    [s('hamstrings'), s('adductors'), b('calves'), b('abs')],
    'dumbbell'),
  e('Step-Up', null, ['quads', 'glutes'],
    [s('hamstrings'), s('adductors'), b('calves'), b('abs')],
    'dumbbell'),
  e('Smith Machine Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs')],
    'smith', { stanceWidth: 'shoulder' }),
  e('Split Squat', null, ['quads', 'glutes'],
    [s('hamstrings'), s('adductors'), b('calves'), b('abs')],
    'dumbbell'),
  e('Seated Leg Curl', null, ['hamstrings'],
    [s('calves')],
    'machine'),
  e('45° Hyperextension', null, ['glutes', 'hamstrings'],
    [s('lowerBack'), b('abs')],
    'bodyweight'),
  e('Glute Bridge', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs')],
    'bodyweight'),
  e('Hip Abduction Machine', null, ['abductors'],
    [],
    'machine'),
  e('Hip Adduction Machine', null, ['adductors'],
    [],
    'machine'),
  e('Machine Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs')],
    'machine'),
  e('Standing Calf Raise (Machine)', null, ['calves'],
    [],
    'machine'),
  e('Seated Calf Raise', null, ['calves'],
    [],
    'machine'),
  e('Cable Crunch', null, ['abs'],
    [],
    'cable'),
  e('Pallof Press', null, ['obliques'],
    [s('abs')],
    'cable'),
  e('Dead Bug', null, ['abs'],
    [s('hipFlexors'), b('obliques')],
    'bodyweight'),
  e('Bird Dog', null, ['abs'],
    [s('obliques'), s('glutes')],
    'bodyweight'),
  e('Side Plank', null, ['obliques'],
    [s('abs'), s('abductors'), b('frontDelts')],
    'bodyweight'),
  e('Hanging Knee Raise', null, ['abs', 'hipFlexors'],
    [b('obliques'), b('forearms')],
    'bodyweight'),
  e("Captain's Chair Knee Raise", null, ['abs', 'hipFlexors'],
    [b('obliques')],
    'machine'),
  e('Machine Tricep Extension', null, ['triceps'],
    [b('forearms')],
    'machine'),

  // ── Session 45e: 25 P5 variants + 53 P2 + 11 P3 = 89 ──
  // P5 — Bench Press variants (2)
  e('Paused Bench Press', 'Bench Press', ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff'), b('lats')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated', bias: 'paused' }),
  e('Spoto Press', 'Bench Press', ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff'), b('lats')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated', bias: 'paused' }),
  // P5 — Squat variants (4)
  e('Low-Bar Back Squat', 'Squat', ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs'), b('calves')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Safety Bar Squat', 'Squat', ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs'), b('calves')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Box Squat', 'Squat', ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs'), b('calves')],
    'barbell', { stanceWidth: 'shoulder', bias: 'paused' }),
  e('Paused Squat', 'Squat', ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings'), b('lowerBack'), b('abs'), b('calves')],
    'barbell', { stanceWidth: 'shoulder', bias: 'paused' }),
  // P5 — Deadlift variants (4)
  e('Rack Pull', 'Deadlift', ['glutes', 'hamstrings'],
    [s('quads'), b('lowerBack'), b('upperBack'), b('forearms')],
    'barbell', { bias: 'partial' }),
  e('Block Pull', 'Deadlift', ['glutes', 'hamstrings'],
    [s('quads'), b('lowerBack'), b('upperBack'), b('forearms')],
    'barbell', { bias: 'partial' }),
  e('Deficit Deadlift', 'Deadlift', ['glutes', 'hamstrings'],
    [s('quads'), b('lowerBack'), b('upperBack'), b('forearms')],
    'barbell', { bias: 'lengthened' }),
  e('Snatch-Grip Deadlift', 'Deadlift', ['glutes', 'hamstrings'],
    [s('quads'), b('lowerBack'), b('upperBack'), b('forearms')],
    'barbell', { gripWidth: 'wide', gripOrientation: 'pronated' }),
  // P5 — Dips variants (3)
  e('Tricep Dips', 'Dips', ['chest', 'triceps'],
    [s('frontDelts'), b('upperBack'), b('rotatorCuff')],
    'bodyweight'),
  e('Chest Dips', 'Dips', ['chest', 'triceps'],
    [s('frontDelts'), b('upperBack'), b('rotatorCuff')],
    'bodyweight'),
  e('Weighted Dip', 'Dips', ['chest', 'triceps'],
    [s('frontDelts'), b('upperBack'), b('rotatorCuff')],
    'bodyweight'),
  // P5 — Lat Pulldown variants (3)
  e('Close-Grip Lat Pulldown', 'Lat Pulldown', ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'cable', { gripWidth: 'narrow', gripOrientation: 'pronated' }),
  e('V-Bar Lat Pulldown', 'Lat Pulldown', ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'cable', { gripWidth: 'narrow', gripOrientation: 'neutral' }),
  e('Reverse-Grip Lat Pulldown', 'Lat Pulldown', ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms')],
    'cable', { gripWidth: 'medium', gripOrientation: 'supinated' }),
  // P5 — RDL variant (1)
  e('Paused RDL', 'Romanian Deadlift', ['glutes', 'hamstrings'],
    [b('upperBack'), b('lowerBack'), b('abs'), b('forearms')],
    'barbell', { bias: 'paused' }),
  // P5 — Pull-Up variant (1) with DIVERGENT map (Rule 1 override)
  e('Narrow-Grip Pull-Up', 'Pull-Up', ['lats', 'biceps'],
    [s('upperBack'), s('brachialis'), s('rearDelts'), b('forearms')],
    'bodyweight', { gripWidth: 'narrow', gripOrientation: 'pronated' }),
  // P5 — Skull Crusher variants (2)
  e('Dumbbell Skull Crusher', 'Skull Crusher', ['triceps'],
    [b('forearms'), b('rotatorCuff')],
    'dumbbell'),
  e('Incline Skull Crusher', 'Skull Crusher', ['triceps'],
    [b('forearms'), b('rotatorCuff')],
    'barbell', { bias: 'lengthened' }),
  // P5 — Barbell Curl variant (1)
  e('Strict Curl', 'Barbell Curl', ['biceps'],
    [s('brachialis'), s('forearms'), b('abs')],
    'barbell', { gripOrientation: 'supinated' }),
  // P5 — Plank variants (2)
  e('Knee Plank', 'Plank', ['abs'],
    [b('obliques'), b('glutes'), b('frontDelts'), b('rotatorCuff')],
    'bodyweight'),
  e('Weighted Plank', 'Plank', ['abs'],
    [b('obliques'), b('glutes'), b('frontDelts'), b('rotatorCuff')],
    'bodyweight'),
  // P5 — Cable Crossover variants (2)
  e('Cable Crossover — High', 'Cable Crossover', ['chest'],
    [s('frontDelts'), b('rotatorCuff')],
    'cable'),
  e('Cable Crossover — Low', 'Cable Crossover', ['chest'],
    [s('frontDelts'), b('rotatorCuff')],
    'cable'),

  // P2 — Chest (5)
  e('Decline Dumbbell Bench Press', null, ['chest'],
    [s('triceps'), s('frontDelts'), b('rotatorCuff')],
    'dumbbell'),
  e('Incline Dumbbell Fly', null, ['chest'],
    [s('frontDelts'), b('rotatorCuff')],
    'dumbbell'),
  e('Dumbbell Pullover', null, ['chest'],
    [s('lats'), s('triceps'), s('serratus')],
    'dumbbell'),
  e('Smith Machine Bench Press', null, ['chest'],
    [s('triceps'), s('frontDelts')],
    'smith', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Smith Machine Incline Bench Press', null, ['chest'],
    [s('frontDelts'), s('triceps')],
    'smith', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  // P2 — Back (7)
  e('Chest-Supported T-Bar Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms')],
    'barbell', { gripOrientation: 'neutral' }),
  e('Pendlay Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Inverted Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('abs'), b('forearms')],
    'bodyweight', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Straight-Arm Pulldown', null, ['lats'],
    [b('triceps'), b('abs')],
    'cable', { gripWidth: 'shoulder', gripOrientation: 'pronated' }),
  e('Single-Arm Lat Pulldown', null, ['lats'],
    [s('upperBack'), s('biceps'), s('brachialis'), s('rearDelts'), b('forearms'), b('obliques')],
    'cable', { gripOrientation: 'neutral' }),
  e('Yates Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'barbell', { gripWidth: 'medium', gripOrientation: 'supinated' }),
  e('Smith Machine Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack')],
    'smith', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  // P2 — Hamstrings (5)
  e('Nordic Curl', null, ['hamstrings'],
    [s('calves'), b('glutes'), b('abs')],
    'bodyweight'),
  e('Glute-Ham Raise', null, ['hamstrings'],
    [s('glutes'), s('calves'), b('abs')],
    'bodyweight'),
  e('Good Morning', null, ['glutes', 'hamstrings'],
    [s('lowerBack'), b('upperBack'), b('abs')],
    'barbell', { stanceWidth: 'shoulder' }),
  e('Single-Leg RDL', null, ['glutes', 'hamstrings'],
    [b('upperBack'), b('lowerBack'), b('abs'), b('obliques'), b('calves')],
    'dumbbell'),
  e('Reverse Hyperextension Machine', null, ['glutes', 'hamstrings'],
    [s('lowerBack')],
    'machine'),
  // P2 — Glutes (7)
  e('Dumbbell Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs')],
    'dumbbell'),
  e('Cable Kickback', null, ['glutes'],
    [s('hamstrings'), b('obliques')],
    'cable'),
  e('Smith Machine Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs')],
    'smith'),
  e('Machine Glute Kickback', null, ['glutes'],
    [s('hamstrings')],
    'machine'),
  e('Single-Leg Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs'), b('obliques')],
    'bodyweight'),
  e('Single-Leg Smith Machine Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs'), b('obliques')],
    'smith'),
  e('Single-Leg Machine Hip Thrust', null, ['glutes'],
    [s('hamstrings'), s('adductors'), b('lowerBack'), b('abs'), b('obliques')],
    'machine'),
  // P2 — Calves (3)
  e('Leg Press Calf Raise', null, ['calves'],
    [],
    'machine'),
  e('Smith Machine Calf Raise', null, ['calves'],
    [],
    'smith'),
  e('Single-Leg Dumbbell Calf Raise', null, ['calves'],
    [],
    'dumbbell'),
  // P2 — Quads (5)
  e('Plate-Loaded Hack Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine', { stanceWidth: 'shoulder' }),
  e('Vertical Leg Press', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine', { stanceWidth: 'shoulder' }),
  e('Forward Lunge', null, ['quads', 'glutes'],
    [s('hamstrings'), s('adductors'), b('calves'), b('abs')],
    'dumbbell'),
  e('Pendulum Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine', { stanceWidth: 'shoulder' }),
  e('Belt Squat', null, ['quads'],
    [s('glutes'), s('adductors'), s('hamstrings')],
    'machine', { stanceWidth: 'shoulder' }),
  // P2 — Shoulders (5)
  e('Machine Lateral Raise', null, ['sideDelts'],
    [s('upperTraps'), b('rotatorCuff')],
    'machine'),
  // Rule 5 dedicated-cuff-isolation primary exception (Cable ER + DB ER)
  e('Cable External Rotation', null, ['rotatorCuff'],
    [],
    'cable'),
  e('Dumbbell External Rotation', null, ['rotatorCuff'],
    [],
    'dumbbell'),
  e('Smith Machine Overhead Press', null, ['frontDelts'],
    [s('sideDelts'), s('triceps'), s('upperTraps'), s('serratus'), b('abs')],
    'smith', { gripWidth: 'medium', gripOrientation: 'pronated' }),
  e('Machine Shrug', null, ['upperTraps'],
    [b('forearms'), b('lowerBack'), b('neck')],
    'machine'),
  // P2 — Biceps (4)
  e('Spider Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'dumbbell', { gripOrientation: 'supinated' }),
  e('Concentration Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'dumbbell', { gripOrientation: 'supinated' }),
  e('Reverse Curl', null, ['biceps', 'brachialis'],
    [s('forearms'), b('abs')],
    'barbell', { gripOrientation: 'pronated' }),
  e('Machine Bicep Curl', null, ['biceps'],
    [s('brachialis'), s('forearms')],
    'machine', { gripOrientation: 'supinated' }),
  // P2 — Triceps (3)
  e('Tricep Kickback', null, ['triceps'],
    [b('rearDelts')],
    'dumbbell', { gripOrientation: 'neutral' }),
  e('Bench Dips', null, ['triceps'],
    [s('frontDelts'), b('rotatorCuff')],
    'bodyweight'),
  e('Seated Tricep Dip Machine', null, ['triceps'],
    [s('frontDelts')],
    'machine'),
  // P2 — Forearms (2)
  e('Wrist Curl', null, ['forearms'],
    [],
    'barbell', { gripOrientation: 'supinated' }),
  e('Reverse Wrist Curl', null, ['forearms'],
    [],
    'barbell', { gripOrientation: 'pronated' }),
  // P2 — Core (5)
  e('Pallof Chop / Lift', null, ['obliques'],
    [s('abs'), b('frontDelts')],
    'cable'),
  e('Hollow Hold', null, ['abs'],
    [s('hipFlexors'), b('obliques')],
    'bodyweight'),
  e('Russian Twist', null, ['obliques'],
    [s('abs'), b('hipFlexors')],
    'bodyweight'),
  e('Decline Sit-Up', null, ['abs', 'hipFlexors'],
    [b('obliques')],
    'bodyweight'),
  e('Ab Crunch Machine', null, ['abs'],
    [],
    'machine'),
  // P2 — Carries (2)
  e('Farmer Carry', null, ['forearms', 'upperTraps'],
    [b('abs'), b('obliques'), b('lowerBack'), s('quads'), s('glutes'), s('calves')],
    'dumbbell', { gripOrientation: 'neutral' }),
  e('Suitcase Carry', null, ['forearms', 'upperTraps'],
    [s('obliques'), b('abs'), b('lowerBack'), s('quads'), s('glutes'), s('calves')],
    'dumbbell', { gripOrientation: 'neutral' }),

  // P3 entries (11)
  e('Meadows Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('lowerBack'), b('obliques')],
    'barbell', { gripOrientation: 'pronated' }),
  e('Sissy Squat', null, ['quads'],
    [b('abs')],
    'bodyweight'),
  e('B-Stance RDL', null, ['glutes', 'hamstrings'],
    [b('upperBack'), b('lowerBack'), b('abs'), b('obliques'), b('forearms')],
    'dumbbell'),
  e('Donkey Calf Raise', null, ['calves'],
    [],
    'bodyweight'),
  e('Tibialis Raise', null, ['tibialis'],
    [],
    'bodyweight'),
  e('Cable Y-Raise', null, ['lowerTraps'],
    [s('rearDelts'), s('upperTraps'), s('serratus')],
    'cable', { gripOrientation: 'neutral' }),
  e('JM Press', null, ['triceps'],
    [s('chest'), s('frontDelts'), b('rotatorCuff')],
    'barbell', { gripWidth: 'narrow', gripOrientation: 'pronated' }),
  e('Wrist Roller', null, ['forearms'],
    [b('frontDelts')],
    'other'),
  e('L-Sit Hold', null, ['abs', 'hipFlexors'],
    [s('triceps'), s('quads'), b('obliques')],
    'bodyweight'),
  e('Overhead Carry', null, ['frontDelts'],
    [s('rotatorCuff'), s('upperTraps'), s('serratus'), s('triceps'), b('abs'), b('obliques'), b('lowerBack'), s('quads'), s('glutes'), s('calves')],
    'kettlebell'),
  e('Zercher Carry', null, ['upperBack', 'biceps'],
    [b('forearms'), b('abs'), b('obliques'), b('lowerBack'), s('quads'), s('glutes'), s('calves')],
    'barbell'),

  // ── Session 45f: 19 P4 plyo + KB + conditioning ──
  e('Box Jump', null, ['quads'],
    [s('glutes'), s('hamstrings'), s('calves')],
    'bodyweight'),
  e('Broad Jump', null, ['quads'],
    [s('glutes'), s('hamstrings'), s('calves')],
    'bodyweight'),
  e('Depth Jump', null, ['quads'],
    [s('calves'), s('glutes'), s('hamstrings')],
    'bodyweight'),
  e('Pogo Hop', null, ['calves'],
    [b('quads')],
    'bodyweight'),
  // Clap Push-Up: variant of Push-Up, inherit map
  e('Clap Push-Up', 'Push-Up', ['chest'],
    [s('triceps'), s('frontDelts'), s('serratus'), b('abs'), b('rotatorCuff')],
    'bodyweight', { bias: 'explosive' }),
  e('Medicine Ball Slam', null, ['lats'],
    [s('abs'), b('frontDelts')],
    'other'),
  e('Medicine Ball Chest Throw', null, ['chest'],
    [s('triceps'), s('frontDelts'), b('abs'), b('rotatorCuff')],
    'other'),
  e('KB Swing', null, ['glutes', 'hamstrings'],
    [b('forearms'), b('lowerBack'), b('abs'), b('upperBack')],
    'kettlebell', { gripOrientation: 'neutral' }),
  e('KB Goblet Squat', null, ['quads'],
    [s('glutes'), s('adductors'), b('lowerBack'), b('abs'), b('upperBack'), b('biceps')],
    'kettlebell', { gripOrientation: 'neutral', stanceWidth: 'shoulder' }),
  e('Turkish Get-Up', null, ['abs', 'obliques'],
    [s('frontDelts'), s('triceps'), b('rotatorCuff'), s('upperTraps'), s('glutes'), s('quads')],
    'kettlebell'),
  e('KB Single-Leg Deadlift', null, ['glutes', 'hamstrings'],
    [s('obliques'), b('lowerBack'), b('forearms'), b('calves')],
    'kettlebell', { gripOrientation: 'neutral' }),
  e('Sled Push', null, ['quads'],
    [s('glutes'), s('calves'), s('chest'), s('triceps'), b('abs')],
    'other'),
  e('Sled Pull', null, ['quads', 'glutes'],
    [s('hamstrings'), s('calves'), b('forearms'), b('abs')],
    'other'),
  e('Assault Bike', null, ['quads'],
    [s('glutes'), s('hamstrings'), s('calves'), s('chest'), s('lats')],
    'machine'),
  e('Rower', null, ['quads'],
    [s('glutes'), s('hamstrings'), s('lats'), s('upperBack'), s('biceps'), b('forearms')],
    'machine'),
  e('Ski Erg', null, ['lats'],
    [s('abs'), s('triceps'), s('lowerTraps'), b('lowerBack')],
    'machine'),
  e('Burpee', null, ['quads'],
    [s('glutes'), s('calves'), s('chest'), s('triceps'), s('frontDelts'), b('abs')],
    'bodyweight'),
  e('Sprint', null, ['hamstrings', 'glutes'],
    [s('quads'), s('calves'), b('abs'), b('obliques')],
    'bodyweight'),
  e('Sled Row', null, ['lats', 'upperBack'],
    [s('rearDelts'), s('biceps'), s('brachialis'), b('forearms'), b('quads'), b('abs')],
    'other', { gripOrientation: 'neutral' }),

  // ── Session 45g: 12 P4 Olympic + KB-ballistic ──
  e('Power Clean', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('frontDelts'), b('lowerBack'), b('forearms'), b('upperBack'), b('abs')],
    'barbell'),
  e('Hang Clean', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('frontDelts'), b('lowerBack'), b('forearms'), b('upperBack'), b('abs')],
    'barbell'),
  e('Clean & Jerk', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('frontDelts'), s('triceps'), s('sideDelts'), s('serratus'), b('lowerBack'), b('forearms'), b('upperBack'), b('abs'), b('rotatorCuff')],
    'barbell'),
  e('Power Snatch', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('frontDelts'), s('triceps'), s('sideDelts'), s('serratus'), s('upperBack'), b('lowerBack'), b('forearms'), b('abs'), b('rotatorCuff')],
    'barbell'),
  e('Hang Snatch', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('frontDelts'), s('triceps'), s('sideDelts'), s('serratus'), s('upperBack'), b('lowerBack'), b('forearms'), b('abs'), b('rotatorCuff')],
    'barbell'),
  e('Clean Pull', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), b('lowerBack'), b('forearms'), b('upperBack')],
    'barbell'),
  e('Snatch Pull', null, ['glutes', 'hamstrings'],
    [s('quads'), s('upperTraps'), s('calves'), s('lats'), s('upperBack'), b('lowerBack'), b('forearms')],
    'barbell'),
  e('Push Jerk', null, ['frontDelts'],
    [s('triceps'), s('sideDelts'), s('upperTraps'), s('serratus'), s('quads'), s('glutes'), s('hamstrings'), s('calves'), b('upperBack'), b('rotatorCuff'), b('abs')],
    'barbell'),
  e('Split Jerk', null, ['frontDelts'],
    [s('triceps'), s('sideDelts'), s('upperTraps'), s('serratus'), s('quads'), s('glutes'), s('hamstrings'), s('calves'), b('upperBack'), b('rotatorCuff'), b('abs')],
    'barbell'),
  e('Push Press', null, ['frontDelts'],
    [s('triceps'), s('sideDelts'), s('upperTraps'), s('serratus'), s('quads'), s('glutes'), s('hamstrings'), s('calves'), b('upperBack'), b('rotatorCuff'), b('abs')],
    'barbell'),
  e('KB Clean', null, ['glutes', 'hamstrings'],
    [b('forearms'), s('frontDelts'), s('upperTraps'), s('calves'), b('lowerBack'), b('abs'), b('obliques')],
    'kettlebell', { gripOrientation: 'neutral' }),
  e('KB Snatch', null, ['glutes', 'hamstrings'],
    [b('forearms'), s('frontDelts'), s('triceps'), s('upperTraps'), s('sideDelts'), s('serratus'), b('lowerBack'), b('abs'), b('obliques'), b('rotatorCuff')],
    'kettlebell', { gripOrientation: 'neutral' }),
];

// ── Insertion ──────────────────────────────────────────────────────────────

/**
 * Populates the exercises table with the 214-entry library on first install.
 * Idempotent: returns early if seedStarted flag set or table already populated.
 * 2-pass: parents inserted first (parentExerciseId: null), then variants resolve
 * parentExerciseId via name lookup against the just-inserted parents.
 * Throws if a variant references an unknown parent name.
 */
export async function seedExercises(): Promise<void> {
  if (seedStarted) return;
  seedStarted = true;
  const count = await db.exercises.count();
  if (count > 0) return;

  const parents = SEED_ENTRIES.filter((entry) => entry.parentName === null);
  const variants = SEED_ENTRIES.filter((entry) => entry.parentName !== null);

  const parentRecords: Omit<Exercise, 'id'>[] = parents.map(({ parentName: _p, ...rest }) => ({
    ...rest,
    parentExerciseId: null,
  }));
  await db.exercises.bulkAdd(parentRecords);

  const inserted = await db.exercises.toArray();
  const nameToId = new Map<string, number>();
  for (const ex of inserted) {
    if (ex.id !== undefined) nameToId.set(ex.name, ex.id);
  }

  const variantRecords: Omit<Exercise, 'id'>[] = variants.map(({ parentName, ...rest }) => {
    const parentId = nameToId.get(parentName!);
    if (parentId === undefined) {
      throw new Error(`Variant "${rest.name}" references unknown parent "${parentName}"`);
    }
    return { ...rest, parentExerciseId: parentId };
  });
  await db.exercises.bulkAdd(variantRecords);
}

/** Test-only: resets the module-level guard so tests can re-run seedExercises after a db.delete(). */
export function _resetSeedFlagForTest(): void {
  seedStarted = false;
}
